// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: adds.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAddsServiceByID = `-- name: GetAddsServiceByID :one
SELECT id, name, description, service_id, service_secret, status, created_at, updated_at, created_by, service_url FROM adds_services WHERE id = $1 AND deleted_at is null
`

type GetAddsServiceByIDRow struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	ServiceID     string
	ServiceSecret string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CreatedBy     uuid.UUID
	ServiceUrl    string
}

func (q *Queries) GetAddsServiceByID(ctx context.Context, id uuid.UUID) (GetAddsServiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getAddsServiceByID, id)
	var i GetAddsServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ServiceID,
		&i.ServiceSecret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.ServiceUrl,
	)
	return i, err
}

const getAddsServiceByServiceID = `-- name: GetAddsServiceByServiceID :one
SELECT id, name, description, service_id, service_secret, status, created_at, updated_at, created_by, service_url FROM adds_services WHERE service_id = $1 AND deleted_at is null
`

type GetAddsServiceByServiceIDRow struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	ServiceID     string
	ServiceSecret string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CreatedBy     uuid.UUID
	ServiceUrl    string
}

func (q *Queries) GetAddsServiceByServiceID(ctx context.Context, serviceID string) (GetAddsServiceByServiceIDRow, error) {
	row := q.db.QueryRow(ctx, getAddsServiceByServiceID, serviceID)
	var i GetAddsServiceByServiceIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ServiceID,
		&i.ServiceSecret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.ServiceUrl,
	)
	return i, err
}

const getAddsServices = `-- name: GetAddsServices :many
select id, service_url, name, service_id, service_secret, description, status, created_by, created_at, updated_at, deleted_at from adds_services where deleted_at is null ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type GetAddsServicesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAddsServices(ctx context.Context, arg GetAddsServicesParams) ([]AddsService, error) {
	rows, err := q.db.Query(ctx, getAddsServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddsService
	for rows.Next() {
		var i AddsService
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.Name,
			&i.ServiceID,
			&i.ServiceSecret,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAddsService = `-- name: SaveAddsService :one
INSERT INTO adds_services (name, description, status, created_by, service_id, service_secret, service_url) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, service_url, name, service_id, service_secret, description, status, created_by, created_at, updated_at, deleted_at
`

type SaveAddsServiceParams struct {
	Name          string
	Description   sql.NullString
	Status        string
	CreatedBy     uuid.UUID
	ServiceID     string
	ServiceSecret string
	ServiceUrl    string
}

func (q *Queries) SaveAddsService(ctx context.Context, arg SaveAddsServiceParams) (AddsService, error) {
	row := q.db.QueryRow(ctx, saveAddsService,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.ServiceID,
		arg.ServiceSecret,
		arg.ServiceUrl,
	)
	var i AddsService
	err := row.Scan(
		&i.ID,
		&i.ServiceUrl,
		&i.Name,
		&i.ServiceID,
		&i.ServiceSecret,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAddsServiceStatus = `-- name: UpdateAddsServiceStatus :one
UPDATE adds_services SET status = $2, updated_at = NOW() WHERE id = $1 AND deleted_at is null RETURNING id, service_url, name, service_id, service_secret, description, status, created_by, created_at, updated_at, deleted_at
`

type UpdateAddsServiceStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateAddsServiceStatus(ctx context.Context, arg UpdateAddsServiceStatusParams) (AddsService, error) {
	row := q.db.QueryRow(ctx, updateAddsServiceStatus, arg.ID, arg.Status)
	var i AddsService
	err := row.Scan(
		&i.ID,
		&i.ServiceUrl,
		&i.Name,
		&i.ServiceID,
		&i.ServiceSecret,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
