// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const checkIfUserAlreadyConverted = `-- name: CheckIfUserAlreadyConverted :one
SELECT EXISTS(
    SELECT 1 FROM agent_referrals 
    WHERE user_id = $1 AND request_id = $2
) as already_converted
`

type CheckIfUserAlreadyConvertedParams struct {
	UserID    uuid.NullUUID
	RequestID string
}

func (q *Queries) CheckIfUserAlreadyConverted(ctx context.Context, arg CheckIfUserAlreadyConvertedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfUserAlreadyConverted, arg.UserID, arg.RequestID)
	var already_converted bool
	err := row.Scan(&already_converted)
	return already_converted, err
}

const countAgentReferralsByRequestID = `-- name: CountAgentReferralsByRequestID :one
SELECT COUNT(*) FROM agent_referrals 
WHERE request_id = $1
`

func (q *Queries) CountAgentReferralsByRequestID(ctx context.Context, requestID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentReferralsByRequestID, requestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferralsByUserID = `-- name: CountReferralsByUserID :one
SELECT COUNT(*) FROM agent_referrals 
WHERE user_id = $1
`

func (q *Queries) CountReferralsByUserID(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReferralsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentProvider = `-- name: CreateAgentProvider :one
INSERT INTO agent_providers (
    client_id,
    client_secret,
    status,
    name,
    description,
    callback_url
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, client_id, client_secret, status, name, description, callback_url, created_at, updated_at, deleted_at
`

type CreateAgentProviderParams struct {
	ClientID     string
	ClientSecret string
	Status       string
	Name         string
	Description  sql.NullString
	CallbackUrl  sql.NullString
}

func (q *Queries) CreateAgentProvider(ctx context.Context, arg CreateAgentProviderParams) (AgentProvider, error) {
	row := q.db.QueryRow(ctx, createAgentProvider,
		arg.ClientID,
		arg.ClientSecret,
		arg.Status,
		arg.Name,
		arg.Description,
		arg.CallbackUrl,
	)
	var i AgentProvider
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.CallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAgentReferralLink = `-- name: CreateAgentReferralLink :one
INSERT INTO agent_referrals (
    request_id,
    callback_url
) VALUES (
    $1, $2
) RETURNING id, request_id, callback_url, user_id, conversion_type, amount, msisdn, converted_at, callback_sent, callback_attempts, created_at, updated_at
`

type CreateAgentReferralLinkParams struct {
	RequestID   string
	CallbackUrl string
}

func (q *Queries) CreateAgentReferralLink(ctx context.Context, arg CreateAgentReferralLinkParams) (AgentReferral, error) {
	row := q.db.QueryRow(ctx, createAgentReferralLink, arg.RequestID, arg.CallbackUrl)
	var i AgentReferral
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.CallbackUrl,
		&i.UserID,
		&i.ConversionType,
		&i.Amount,
		&i.Msisdn,
		&i.ConvertedAt,
		&i.CallbackSent,
		&i.CallbackAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentProviderByClientID = `-- name: GetAgentProviderByClientID :one
SELECT id, client_id, client_secret, status, name, description, callback_url, created_at, updated_at, deleted_at FROM agent_providers WHERE client_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgentProviderByClientID(ctx context.Context, clientID string) (AgentProvider, error) {
	row := q.db.QueryRow(ctx, getAgentProviderByClientID, clientID)
	var i AgentProvider
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.CallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgentProviderByID = `-- name: GetAgentProviderByID :one
SELECT id, client_id, client_secret, status, name, description, callback_url, created_at, updated_at, deleted_at FROM agent_providers WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgentProviderByID(ctx context.Context, id uuid.UUID) (AgentProvider, error) {
	row := q.db.QueryRow(ctx, getAgentProviderByID, id)
	var i AgentProvider
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.CallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgentReferralByRequestID = `-- name: GetAgentReferralByRequestID :one
SELECT id, request_id, callback_url, user_id, conversion_type, amount, msisdn, converted_at, callback_sent, callback_attempts, created_at, updated_at FROM agent_referrals 
WHERE request_id = $1
`

func (q *Queries) GetAgentReferralByRequestID(ctx context.Context, requestID string) (AgentReferral, error) {
	row := q.db.QueryRow(ctx, getAgentReferralByRequestID, requestID)
	var i AgentReferral
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.CallbackUrl,
		&i.UserID,
		&i.ConversionType,
		&i.Amount,
		&i.Msisdn,
		&i.ConvertedAt,
		&i.CallbackSent,
		&i.CallbackAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentReferralsByRequestID = `-- name: GetAgentReferralsByRequestID :many
SELECT id, request_id, callback_url, user_id, conversion_type, amount, msisdn, converted_at, callback_sent, callback_attempts, created_at, updated_at FROM agent_referrals 
WHERE request_id = $1
ORDER BY converted_at DESC
LIMIT $2 OFFSET $3
`

type GetAgentReferralsByRequestIDParams struct {
	RequestID string
	Limit     int32
	Offset    int32
}

func (q *Queries) GetAgentReferralsByRequestID(ctx context.Context, arg GetAgentReferralsByRequestIDParams) ([]AgentReferral, error) {
	rows, err := q.db.Query(ctx, getAgentReferralsByRequestID, arg.RequestID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentReferral
	for rows.Next() {
		var i AgentReferral
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.CallbackUrl,
			&i.UserID,
			&i.ConversionType,
			&i.Amount,
			&i.Msisdn,
			&i.ConvertedAt,
			&i.CallbackSent,
			&i.CallbackAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingCallbacks = `-- name: GetPendingCallbacks :many
SELECT id, request_id, callback_url, user_id, conversion_type, amount, msisdn, converted_at, callback_sent, callback_attempts, created_at, updated_at FROM agent_referrals
WHERE callback_sent = false 
AND callback_attempts < 3
AND user_id IS NOT NULL
AND callback_url IS NOT NULL
AND TRIM(callback_url) <> ''
ORDER BY converted_at ASC
LIMIT $1 OFFSET $2
`

type GetPendingCallbacksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPendingCallbacks(ctx context.Context, arg GetPendingCallbacksParams) ([]AgentReferral, error) {
	rows, err := q.db.Query(ctx, getPendingCallbacks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentReferral
	for rows.Next() {
		var i AgentReferral
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.CallbackUrl,
			&i.UserID,
			&i.ConversionType,
			&i.Amount,
			&i.Msisdn,
			&i.ConvertedAt,
			&i.CallbackSent,
			&i.CallbackAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReferralStatsByConversionType = `-- name: GetReferralStatsByConversionType :many
SELECT 
    conversion_type,
    COUNT(*) as total_conversions,
    SUM(amount) as total_amount
FROM agent_referrals 
WHERE request_id = $1 AND user_id IS NOT NULL
GROUP BY conversion_type
`

type GetReferralStatsByConversionTypeRow struct {
	ConversionType   sql.NullString
	TotalConversions int64
	TotalAmount      int64
}

func (q *Queries) GetReferralStatsByConversionType(ctx context.Context, requestID string) ([]GetReferralStatsByConversionTypeRow, error) {
	rows, err := q.db.Query(ctx, getReferralStatsByConversionType, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReferralStatsByConversionTypeRow
	for rows.Next() {
		var i GetReferralStatsByConversionTypeRow
		if err := rows.Scan(&i.ConversionType, &i.TotalConversions, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReferralStatsByRequestID = `-- name: GetReferralStatsByRequestID :one
SELECT 
    COUNT(*) as total_conversions,
    SUM(amount) as total_amount,
    COUNT(DISTINCT user_id) as unique_users
FROM agent_referrals 
WHERE request_id = $1 AND user_id IS NOT NULL
`

type GetReferralStatsByRequestIDRow struct {
	TotalConversions int64
	TotalAmount      int64
	UniqueUsers      int64
}

func (q *Queries) GetReferralStatsByRequestID(ctx context.Context, requestID string) (GetReferralStatsByRequestIDRow, error) {
	row := q.db.QueryRow(ctx, getReferralStatsByRequestID, requestID)
	var i GetReferralStatsByRequestIDRow
	err := row.Scan(&i.TotalConversions, &i.TotalAmount, &i.UniqueUsers)
	return i, err
}

const getReferralsByUserID = `-- name: GetReferralsByUserID :many
SELECT id, request_id, callback_url, user_id, conversion_type, amount, msisdn, converted_at, callback_sent, callback_attempts, created_at, updated_at FROM agent_referrals 
WHERE user_id = $1
ORDER BY converted_at DESC
LIMIT $2 OFFSET $3
`

type GetReferralsByUserIDParams struct {
	UserID uuid.NullUUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetReferralsByUserID(ctx context.Context, arg GetReferralsByUserIDParams) ([]AgentReferral, error) {
	rows, err := q.db.Query(ctx, getReferralsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentReferral
	for rows.Next() {
		var i AgentReferral
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.CallbackUrl,
			&i.UserID,
			&i.ConversionType,
			&i.Amount,
			&i.Msisdn,
			&i.ConvertedAt,
			&i.CallbackSent,
			&i.CallbackAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCallbackAttempts = `-- name: IncrementCallbackAttempts :exec
UPDATE agent_referrals 
SET callback_attempts = callback_attempts + 1 
WHERE id = $1
`

func (q *Queries) IncrementCallbackAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCallbackAttempts, id)
	return err
}

const listAgentProviders = `-- name: ListAgentProviders :many
SELECT id, client_id, client_secret, status, name, description, callback_url, created_at, updated_at, deleted_at FROM agent_providers WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAgentProvidersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAgentProviders(ctx context.Context, arg ListAgentProvidersParams) ([]AgentProvider, error) {
	rows, err := q.db.Query(ctx, listAgentProviders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentProvider
	for rows.Next() {
		var i AgentProvider
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecret,
			&i.Status,
			&i.Name,
			&i.Description,
			&i.CallbackUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCallbackSent = `-- name: MarkCallbackSent :exec
UPDATE agent_referrals 
SET callback_sent = true 
WHERE id = $1
`

func (q *Queries) MarkCallbackSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCallbackSent, id)
	return err
}

const updateAgentProviderStatus = `-- name: UpdateAgentProviderStatus :exec
UPDATE agent_providers SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAgentProviderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateAgentProviderStatus(ctx context.Context, arg UpdateAgentProviderStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgentProviderStatus, arg.ID, arg.Status)
	return err
}

const updateAgentReferralWithConversion = `-- name: UpdateAgentReferralWithConversion :one
UPDATE agent_referrals 
SET user_id = $2, conversion_type = $3, amount = $4, msisdn = $5
WHERE request_id = $1
RETURNING id, request_id, callback_url, user_id, conversion_type, amount, msisdn, converted_at, callback_sent, callback_attempts, created_at, updated_at
`

type UpdateAgentReferralWithConversionParams struct {
	RequestID      string
	UserID         uuid.NullUUID
	ConversionType sql.NullString
	Amount         decimal.NullDecimal
	Msisdn         sql.NullString
}

func (q *Queries) UpdateAgentReferralWithConversion(ctx context.Context, arg UpdateAgentReferralWithConversionParams) (AgentReferral, error) {
	row := q.db.QueryRow(ctx, updateAgentReferralWithConversion,
		arg.RequestID,
		arg.UserID,
		arg.ConversionType,
		arg.Amount,
		arg.Msisdn,
	)
	var i AgentReferral
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.CallbackUrl,
		&i.UserID,
		&i.ConversionType,
		&i.Amount,
		&i.Msisdn,
		&i.ConvertedAt,
		&i.CallbackSent,
		&i.CallbackAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
