// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: balancelogs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getBalanceLogByID = `-- name: GetBalanceLogByID :one
SELECT
    bl.id,
    bl.user_id,
    bl.component,
    bl.currency,
    bl.description,
    bl.change_amount,
    bl.operational_group_id,
    ops.name AS type,
    bl.operational_type_id,
    ot.name AS operational_type_name,
    bl.timestamp,
    bl.balance_after_update,
    bl.transaction_id,
    bl.status
FROM
    balance_logs bl
JOIN
    operational_groups ops ON ops.id = bl.operational_group_id
JOIN
    operational_types ot ON ot.id = bl.operational_type_id
WHERE
    bl.id = $1
`

type GetBalanceLogByIDRow struct {
	ID                  uuid.UUID
	UserID              uuid.NullUUID
	Component           Components
	Currency            sql.NullString
	Description         sql.NullString
	ChangeAmount        decimal.NullDecimal
	OperationalGroupID  uuid.NullUUID
	Type                sql.NullString
	OperationalTypeID   uuid.NullUUID
	OperationalTypeName sql.NullString
	Timestamp           sql.NullTime
	BalanceAfterUpdate  decimal.Decimal
	TransactionID       string
	Status              sql.NullString
}

func (q *Queries) GetBalanceLogByID(ctx context.Context, id uuid.UUID) (GetBalanceLogByIDRow, error) {
	row := q.db.QueryRow(ctx, getBalanceLogByID, id)
	var i GetBalanceLogByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Component,
		&i.Currency,
		&i.Description,
		&i.ChangeAmount,
		&i.OperationalGroupID,
		&i.Type,
		&i.OperationalTypeID,
		&i.OperationalTypeName,
		&i.Timestamp,
		&i.BalanceAfterUpdate,
		&i.TransactionID,
		&i.Status,
	)
	return i, err
}

const getBalanceLogByTransactionID = `-- name: GetBalanceLogByTransactionID :one
SELECT
    bl.id,
    bl.user_id,
    bl.component,
    bl.currency,
    bl.description,
    bl.change_amount,
    bl.operational_group_id,
    ops.name AS type,
    bl.operational_type_id,
    ot.name AS operational_type_name,
    bl.timestamp,
    bl.balance_after_update,
    bl.transaction_id,
    bl.status
FROM
    balance_logs bl
JOIN
    operational_groups ops ON ops.id = bl.operational_group_id
JOIN
    operational_types ot ON ot.id = bl.operational_type_id
WHERE
    bl.transaction_id = $1
`

type GetBalanceLogByTransactionIDRow struct {
	ID                  uuid.UUID
	UserID              uuid.NullUUID
	Component           Components
	Currency            sql.NullString
	Description         sql.NullString
	ChangeAmount        decimal.NullDecimal
	OperationalGroupID  uuid.NullUUID
	Type                sql.NullString
	OperationalTypeID   uuid.NullUUID
	OperationalTypeName sql.NullString
	Timestamp           sql.NullTime
	BalanceAfterUpdate  decimal.Decimal
	TransactionID       string
	Status              sql.NullString
}

func (q *Queries) GetBalanceLogByTransactionID(ctx context.Context, transactionID string) (GetBalanceLogByTransactionIDRow, error) {
	row := q.db.QueryRow(ctx, getBalanceLogByTransactionID, transactionID)
	var i GetBalanceLogByTransactionIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Component,
		&i.Currency,
		&i.Description,
		&i.ChangeAmount,
		&i.OperationalGroupID,
		&i.Type,
		&i.OperationalTypeID,
		&i.OperationalTypeName,
		&i.Timestamp,
		&i.BalanceAfterUpdate,
		&i.TransactionID,
		&i.Status,
	)
	return i, err
}
