// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: balance.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const balanceExist = `-- name: BalanceExist :one
SELECT EXISTS (
    SELECT 1 
    FROM balances 
    WHERE user_id = $1 AND currency_code = $2
) AS exists
`

type BalanceExistParams struct {
	UserID       uuid.UUID
	CurrencyCode string
}

func (q *Queries) BalanceExist(ctx context.Context, arg BalanceExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, balanceExist, arg.UserID, arg.CurrencyCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBalance = `-- name: CreateBalance :one
INSERT INTO balances(user_id,currency_code,real_money,bonus_money,points,updated_at) VALUES 
($1,$2,$3,$4,$5,$6) RETURNING id, user_id, currency_code, real_money, bonus_money, points, updated_at
`

type CreateBalanceParams struct {
	UserID       uuid.UUID
	CurrencyCode string
	RealMoney    decimal.Decimal
	BonusMoney   decimal.Decimal
	Points       int32
	UpdatedAt    time.Time
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, createBalance,
		arg.UserID,
		arg.CurrencyCode,
		arg.RealMoney,
		arg.BonusMoney,
		arg.Points,
		arg.UpdatedAt,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrencyCode,
		&i.RealMoney,
		&i.BonusMoney,
		&i.Points,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBalanaceByUserIDAndCurrency = `-- name: GetUserBalanaceByUserIDAndCurrency :one
SELECT id, user_id, currency_code, real_money, bonus_money, points, updated_at FROM balances where user_id = $1 and currency_code=$2
`

type GetUserBalanaceByUserIDAndCurrencyParams struct {
	UserID       uuid.UUID
	CurrencyCode string
}

func (q *Queries) GetUserBalanaceByUserIDAndCurrency(ctx context.Context, arg GetUserBalanaceByUserIDAndCurrencyParams) (Balance, error) {
	row := q.db.QueryRow(ctx, getUserBalanaceByUserIDAndCurrency, arg.UserID, arg.CurrencyCode)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrencyCode,
		&i.RealMoney,
		&i.BonusMoney,
		&i.Points,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBalancesByUserID = `-- name: GetUserBalancesByUserID :many
SELECT id, user_id, currency_code, real_money, bonus_money, points, updated_at FROM  balances where user_id = $1
`

func (q *Queries) GetUserBalancesByUserID(ctx context.Context, userID uuid.UUID) ([]Balance, error) {
	rows, err := q.db.Query(ctx, getUserBalancesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CurrencyCode,
			&i.RealMoney,
			&i.BonusMoney,
			&i.Points,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalance = `-- name: LockBalance :one
SELECT id, user_id, currency_code, real_money, bonus_money, points, updated_at FROM balances 
WHERE user_id = $1 and currency_code = $2
FOR UPDATE
`

type LockBalanceParams struct {
	UserID       uuid.UUID
	CurrencyCode string
}

func (q *Queries) LockBalance(ctx context.Context, arg LockBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, lockBalance, arg.UserID, arg.CurrencyCode)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrencyCode,
		&i.RealMoney,
		&i.BonusMoney,
		&i.Points,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAmountUnits = `-- name: UpdateAmountUnits :one
UPDATE balances set real_money = $1, bonus_money = $2, updated_at=$3 where user_id = $4 and currency_code = $5
RETURNING id, user_id, currency_code, real_money, bonus_money, points, updated_at
`

type UpdateAmountUnitsParams struct {
	RealMoney    decimal.Decimal
	BonusMoney   decimal.Decimal
	UpdatedAt    time.Time
	UserID       uuid.UUID
	CurrencyCode string
}

func (q *Queries) UpdateAmountUnits(ctx context.Context, arg UpdateAmountUnitsParams) (Balance, error) {
	row := q.db.QueryRow(ctx, updateAmountUnits,
		arg.RealMoney,
		arg.BonusMoney,
		arg.UpdatedAt,
		arg.UserID,
		arg.CurrencyCode,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrencyCode,
		&i.RealMoney,
		&i.BonusMoney,
		&i.Points,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE balances set currency_code = $1,real_money=$2,bonus_money=$3,points=$4,updated_at=$5 where user_id = $6
RETURNING id, user_id, currency_code, real_money, bonus_money, points, updated_at
`

type UpdateBalanceParams struct {
	CurrencyCode string
	RealMoney    decimal.Decimal
	BonusMoney   decimal.Decimal
	Points       int32
	UpdatedAt    time.Time
	UserID       uuid.UUID
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, updateBalance,
		arg.CurrencyCode,
		arg.RealMoney,
		arg.BonusMoney,
		arg.Points,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrencyCode,
		&i.RealMoney,
		&i.BonusMoney,
		&i.Points,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReservedUnits = `-- name: UpdateReservedUnits :one
UPDATE balances set points = $1, updated_at=$2 where user_id = $3 and currency_code = $4
RETURNING id, user_id, currency_code, real_money, bonus_money, points, updated_at
`

type UpdateReservedUnitsParams struct {
	Points       int32
	UpdatedAt    time.Time
	UserID       uuid.UUID
	CurrencyCode string
}

func (q *Queries) UpdateReservedUnits(ctx context.Context, arg UpdateReservedUnitsParams) (Balance, error) {
	row := q.db.QueryRow(ctx, updateReservedUnits,
		arg.Points,
		arg.UpdatedAt,
		arg.UserID,
		arg.CurrencyCode,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrencyCode,
		&i.RealMoney,
		&i.BonusMoney,
		&i.Points,
		&i.UpdatedAt,
	)
	return i, err
}
