// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: banner.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBanner = `-- name: CreateBanner :one
INSERT INTO banners (page, page_url, image_url, headline, tagline, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, page, page_url, image_url, headline, tagline, updated_at
`

type CreateBannerParams struct {
	Page     string
	PageUrl  string
	ImageUrl string
	Headline string
	Tagline  sql.NullString
}

type CreateBannerRow struct {
	ID        uuid.UUID
	Page      string
	PageUrl   string
	ImageUrl  string
	Headline  string
	Tagline   sql.NullString
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateBanner(ctx context.Context, arg CreateBannerParams) (CreateBannerRow, error) {
	row := q.db.QueryRow(ctx, createBanner,
		arg.Page,
		arg.PageUrl,
		arg.ImageUrl,
		arg.Headline,
		arg.Tagline,
	)
	var i CreateBannerRow
	err := row.Scan(
		&i.ID,
		&i.Page,
		&i.PageUrl,
		&i.ImageUrl,
		&i.Headline,
		&i.Tagline,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBanner = `-- name: DeleteBanner :exec
DELETE FROM banners
WHERE id = $1
`

func (q *Queries) DeleteBanner(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBanner, id)
	return err
}

const getAllBanners = `-- name: GetAllBanners :many
SELECT 
    id, page, page_url, image_url, headline, tagline, updated_at,
    COUNT(*) OVER() AS total
FROM banners
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type GetAllBannersParams struct {
	Limit  int32
	Offset int32
}

type GetAllBannersRow struct {
	ID        uuid.UUID
	Page      string
	PageUrl   string
	ImageUrl  string
	Headline  string
	Tagline   sql.NullString
	UpdatedAt sql.NullTime
	Total     int64
}

func (q *Queries) GetAllBanners(ctx context.Context, arg GetAllBannersParams) ([]GetAllBannersRow, error) {
	rows, err := q.db.Query(ctx, getAllBanners, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBannersRow
	for rows.Next() {
		var i GetAllBannersRow
		if err := rows.Scan(
			&i.ID,
			&i.Page,
			&i.PageUrl,
			&i.ImageUrl,
			&i.Headline,
			&i.Tagline,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBannerByID = `-- name: GetBannerByID :one
SELECT id, page, page_url, image_url, headline, tagline, updated_at
FROM banners
WHERE id = $1
`

type GetBannerByIDRow struct {
	ID        uuid.UUID
	Page      string
	PageUrl   string
	ImageUrl  string
	Headline  string
	Tagline   sql.NullString
	UpdatedAt sql.NullTime
}

func (q *Queries) GetBannerByID(ctx context.Context, id uuid.UUID) (GetBannerByIDRow, error) {
	row := q.db.QueryRow(ctx, getBannerByID, id)
	var i GetBannerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Page,
		&i.PageUrl,
		&i.ImageUrl,
		&i.Headline,
		&i.Tagline,
		&i.UpdatedAt,
	)
	return i, err
}

const getBannerByPage = `-- name: GetBannerByPage :one
SELECT id, page, page_url, image_url, headline, tagline, updated_at
FROM banners
WHERE page = $1
ORDER BY updated_at DESC
LIMIT 1
`

type GetBannerByPageRow struct {
	ID        uuid.UUID
	Page      string
	PageUrl   string
	ImageUrl  string
	Headline  string
	Tagline   sql.NullString
	UpdatedAt sql.NullTime
}

func (q *Queries) GetBannerByPage(ctx context.Context, page string) (GetBannerByPageRow, error) {
	row := q.db.QueryRow(ctx, getBannerByPage, page)
	var i GetBannerByPageRow
	err := row.Scan(
		&i.ID,
		&i.Page,
		&i.PageUrl,
		&i.ImageUrl,
		&i.Headline,
		&i.Tagline,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBanner = `-- name: UpdateBanner :one
UPDATE banners
SET page_url = $2, image_url = $3, headline = $4, tagline = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, page, page_url, image_url, headline, tagline, updated_at
`

type UpdateBannerParams struct {
	ID       uuid.UUID
	PageUrl  string
	ImageUrl string
	Headline string
	Tagline  sql.NullString
}

type UpdateBannerRow struct {
	ID        uuid.UUID
	Page      string
	PageUrl   string
	ImageUrl  string
	Headline  string
	Tagline   sql.NullString
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateBanner(ctx context.Context, arg UpdateBannerParams) (UpdateBannerRow, error) {
	row := q.db.QueryRow(ctx, updateBanner,
		arg.ID,
		arg.PageUrl,
		arg.ImageUrl,
		arg.Headline,
		arg.Tagline,
	)
	var i UpdateBannerRow
	err := row.Scan(
		&i.ID,
		&i.Page,
		&i.PageUrl,
		&i.ImageUrl,
		&i.Headline,
		&i.Tagline,
		&i.UpdatedAt,
	)
	return i, err
}
