// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: brand.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (name, code, domain, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, name, code, domain, is_active, created_at, updated_at
`

type CreateBrandParams struct {
	Name     string
	Code     string
	Domain   sql.NullString
	IsActive bool
}

type CreateBrandRow struct {
	ID        uuid.UUID
	Name      string
	Code      string
	Domain    sql.NullString
	IsActive  bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (CreateBrandRow, error) {
	row := q.db.QueryRow(ctx, createBrand,
		arg.Name,
		arg.Code,
		arg.Domain,
		arg.IsActive,
	)
	var i CreateBrandRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Domain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBrand = `-- name: DeleteBrand :exec
DELETE FROM brands
WHERE id = $1
`

func (q *Queries) DeleteBrand(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBrand, id)
	return err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name, code, domain, is_active, created_at, updated_at
FROM brands
WHERE id = $1
`

type GetBrandByIDRow struct {
	ID        uuid.UUID
	Name      string
	Code      string
	Domain     sql.NullString
	IsActive  bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetBrandByID(ctx context.Context, id uuid.UUID) (GetBrandByIDRow, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i GetBrandByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Domain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrands = `-- name: GetBrands :many
SELECT 
    id, name, code, domain, is_active, created_at, updated_at,
    COUNT(*) OVER() AS total
FROM brands
WHERE 
    ($1::text IS NULL OR name ILIKE '%' || $1 || '%' OR code ILIKE '%' || $1 || '%') AND
    ($2::bool IS NULL OR is_active = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetBrandsParams struct {
	Column1 sql.NullString
	Column2 sql.NullBool
	Limit   int32
	Offset  int32
}

type GetBrandsRow struct {
	ID        uuid.UUID
	Name      string
	Code      string
	Domain    sql.NullString
	IsActive  bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Total     int64
}

func (q *Queries) GetBrands(ctx context.Context, arg GetBrandsParams) ([]GetBrandsRow, error) {
	rows, err := q.db.Query(ctx, getBrands,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBrandsRow
	for rows.Next() {
		var i GetBrandsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Domain,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE brands
SET 
    name = COALESCE($2, name),
    code = COALESCE($3, code),
    domain = COALESCE($4, domain),
    is_active = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, code, domain, is_active, created_at, updated_at
`

type UpdateBrandParams struct {
	ID       uuid.UUID
	Column2  sql.NullString
	Column3  sql.NullString
	Column4  sql.NullString
	Column5  sql.NullBool
}

type UpdateBrandRow struct {
	ID        uuid.UUID
	Name      string
	Code      string
	Domain    sql.NullString
	IsActive  bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (UpdateBrandRow, error) {
	row := q.db.QueryRow(ctx, updateBrand,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i UpdateBrandRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Domain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

