// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exchange.sql

package db

import (
	"context"
	"database/sql"
)

const getExchangesFromTo = `-- name: GetExchangesFromTo :one
SELECT id, currency_from, currency_to, rate, updated_at FROM exchange_rates where currency_from = $1 and currency_to = $2
`

type GetExchangesFromToParams struct {
	CurrencyFrom sql.NullString
	CurrencyTo   sql.NullString
}

func (q *Queries) GetExchangesFromTo(ctx context.Context, arg GetExchangesFromToParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getExchangesFromTo, arg.CurrencyFrom, arg.CurrencyTo)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CurrencyFrom,
		&i.CurrencyTo,
		&i.Rate,
		&i.UpdatedAt,
	)
	return i, err
}
