// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lottery_service.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createLotteryService = `-- name: CreateLotteryService :one
INSERT INTO lottery_services (id, name, description,client_id,client_secret ,created_at, updated_at,callback_url)
VALUES (gen_random_uuid(), $1, $2,$3,$4 ,NOW(), NOW(),$5)
RETURNING id, name, description, created_at, updated_at
`

type CreateLotteryServiceParams struct {
	Name         string
	Description  sql.NullString
	ClientID     string
	ClientSecret string
	CallbackUrl  sql.NullString
}

type CreateLotteryServiceRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateLotteryService(ctx context.Context, arg CreateLotteryServiceParams) (CreateLotteryServiceRow, error) {
	row := q.db.QueryRow(ctx, createLotteryService,
		arg.Name,
		arg.Description,
		arg.ClientID,
		arg.ClientSecret,
		arg.CallbackUrl,
	)
	var i CreateLotteryServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLotteryService = `-- name: DeleteLotteryService :exec
UPDATE lottery_services
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteLotteryService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLotteryService, id)
	return err
}

const getLotteryServiceByClientID = `-- name: GetLotteryServiceByClientID :one
SELECT id, name, description,client_id,client_id, created_at, updated_at,callback_url
FROM lottery_services
WHERE client_id = $1 AND deleted_at IS NULL
`

type GetLotteryServiceByClientIDRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	ClientID    string
	ClientID_2  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CallbackUrl sql.NullString
}

func (q *Queries) GetLotteryServiceByClientID(ctx context.Context, clientID string) (GetLotteryServiceByClientIDRow, error) {
	row := q.db.QueryRow(ctx, getLotteryServiceByClientID, clientID)
	var i GetLotteryServiceByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.ClientID_2,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CallbackUrl,
	)
	return i, err
}

const getLotteryServiceByID = `-- name: GetLotteryServiceByID :one
SELECT id, name, description, created_at, updated_at,callback_url, client_id, client_secret
FROM lottery_services
WHERE id = $1
`

type GetLotteryServiceByIDRow struct {
	ID           uuid.UUID
	Name         string
	Description  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CallbackUrl  sql.NullString
	ClientID     string
	ClientSecret string
}

func (q *Queries) GetLotteryServiceByID(ctx context.Context, id uuid.UUID) (GetLotteryServiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getLotteryServiceByID, id)
	var i GetLotteryServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CallbackUrl,
		&i.ClientID,
		&i.ClientSecret,
	)
	return i, err
}

const listLotteryServices = `-- name: ListLotteryServices :many
SELECT id, name, description, created_at, updated_at
FROM lottery_services
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListLotteryServicesParams struct {
	Limit  int32
	Offset int32
}

type ListLotteryServicesRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListLotteryServices(ctx context.Context, arg ListLotteryServicesParams) ([]ListLotteryServicesRow, error) {
	rows, err := q.db.Query(ctx, listLotteryServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLotteryServicesRow
	for rows.Next() {
		var i ListLotteryServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLotteryService = `-- name: UpdateLotteryService :one
UPDATE lottery_services
SET name = $1, description = $2, updated_at = NOW()
WHERE id = $3
RETURNING id, name, description, created_at, updated_at
`

type UpdateLotteryServiceParams struct {
	Name        string
	Description sql.NullString
	ID          uuid.UUID
}

type UpdateLotteryServiceRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateLotteryService(ctx context.Context, arg UpdateLotteryServiceParams) (UpdateLotteryServiceRow, error) {
	row := q.db.QueryRow(ctx, updateLotteryService, arg.Name, arg.Description, arg.ID)
	var i UpdateLotteryServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLotteryServiceStatus = `-- name: UpdateLotteryServiceStatus :one
UPDATE lottery_services
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, status, updated_at
`

type UpdateLotteryServiceStatusParams struct {
	Status string
	ID     uuid.UUID
}

type UpdateLotteryServiceStatusRow struct {
	ID        uuid.UUID
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateLotteryServiceStatus(ctx context.Context, arg UpdateLotteryServiceStatusParams) (UpdateLotteryServiceStatusRow, error) {
	row := q.db.QueryRow(ctx, updateLotteryServiceStatus, arg.Status, arg.ID)
	var i UpdateLotteryServiceStatusRow
	err := row.Scan(&i.ID, &i.Status, &i.UpdatedAt)
	return i, err
}
