// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lottery.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createLottery = `-- name: CreateLottery :one
INSERT INTO lotteries (id, name, price, min_selectable, max_selectable, draw_frequency, number_of_balls, description, status, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, 'active', NOW(), NOW())
RETURNING id, name, price, min_selectable, max_selectable, draw_frequency, number_of_balls, description, status, created_at, updated_at
`

type CreateLotteryParams struct {
	Name          string
	Price         decimal.Decimal
	MinSelectable int32
	MaxSelectable int32
	DrawFrequency string
	NumberOfBalls int32
	Description   string
}

func (q *Queries) CreateLottery(ctx context.Context, arg CreateLotteryParams) (Lottery, error) {
	row := q.db.QueryRow(ctx, createLottery,
		arg.Name,
		arg.Price,
		arg.MinSelectable,
		arg.MaxSelectable,
		arg.DrawFrequency,
		arg.NumberOfBalls,
		arg.Description,
	)
	var i Lottery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.MinSelectable,
		&i.MaxSelectable,
		&i.DrawFrequency,
		&i.NumberOfBalls,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLotteryLog = `-- name: CreateLotteryLog :one
INSERT INTO lottery_logs (id, lottery_id, lottery_reward_id, draw_numbers, prize, created_at, updated_at, uniq_identifier)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW(), NOW(), $5)
RETURNING id, lottery_id, lottery_reward_id, draw_numbers, prize, created_at, updated_at
`

type CreateLotteryLogParams struct {
	LotteryID       uuid.UUID
	LotteryRewardID uuid.UUID
	DrawNumbers     [][]int32
	Prize           decimal.Decimal
	UniqIdentifier  uuid.UUID
}

type CreateLotteryLogRow struct {
	ID              uuid.UUID
	LotteryID       uuid.UUID
	LotteryRewardID uuid.UUID
	DrawNumbers     [][]int32
	Prize           decimal.Decimal
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateLotteryLog(ctx context.Context, arg CreateLotteryLogParams) (CreateLotteryLogRow, error) {
	row := q.db.QueryRow(ctx, createLotteryLog,
		arg.LotteryID,
		arg.LotteryRewardID,
		arg.DrawNumbers,
		arg.Prize,
		arg.UniqIdentifier,
	)
	var i CreateLotteryLogRow
	err := row.Scan(
		&i.ID,
		&i.LotteryID,
		&i.LotteryRewardID,
		&i.DrawNumbers,
		&i.Prize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLotteryWinnersLog = `-- name: CreateLotteryWinnersLog :one
INSERT INTO lottery_winners_logs (id, lottery_id, user_id, reward_id, won_amount, currency, ticket_number, status, created_at, updated_at,number_of_tickets)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, 'closed', NOW(), NOW(), $7)
RETURNING id, lottery_id, user_id, reward_id, won_amount, currency, ticket_number, status, created_at, updated_at
`

type CreateLotteryWinnersLogParams struct {
	LotteryID       uuid.UUID
	UserID          uuid.UUID
	RewardID        uuid.UUID
	WonAmount       decimal.Decimal
	Currency        string
	TicketNumber    string
	NumberOfTickets int32
}

type CreateLotteryWinnersLogRow struct {
	ID           uuid.UUID
	LotteryID    uuid.UUID
	UserID       uuid.UUID
	RewardID     uuid.UUID
	WonAmount    decimal.Decimal
	Currency     string
	TicketNumber string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateLotteryWinnersLog(ctx context.Context, arg CreateLotteryWinnersLogParams) (CreateLotteryWinnersLogRow, error) {
	row := q.db.QueryRow(ctx, createLotteryWinnersLog,
		arg.LotteryID,
		arg.UserID,
		arg.RewardID,
		arg.WonAmount,
		arg.Currency,
		arg.TicketNumber,
		arg.NumberOfTickets,
	)
	var i CreateLotteryWinnersLogRow
	err := row.Scan(
		&i.ID,
		&i.LotteryID,
		&i.UserID,
		&i.RewardID,
		&i.WonAmount,
		&i.Currency,
		&i.TicketNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailableLotteryService = `-- name: GetAvailableLotteryService :one
SELECT id, client_id, client_secret, status, name, description, callback_url, created_at, updated_at, deleted_at
FROM lottery_services
WHERE status = 'active' AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetAvailableLotteryService(ctx context.Context) (LotteryService, error) {
	row := q.db.QueryRow(ctx, getAvailableLotteryService)
	var i LotteryService
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.CallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLotteryByID = `-- name: GetLotteryByID :one
SELECT id, name, price, min_selectable, max_selectable, draw_frequency, number_of_balls, description, status, created_at, updated_at
FROM lotteries
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLotteryByID(ctx context.Context, id uuid.UUID) (Lottery, error) {
	row := q.db.QueryRow(ctx, getLotteryByID, id)
	var i Lottery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.MinSelectable,
		&i.MaxSelectable,
		&i.DrawFrequency,
		&i.NumberOfBalls,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLotteryLogsByUniqIdentifier = `-- name: GetLotteryLogsByUniqIdentifier :many
SELECT id, lottery_id, lottery_reward_id, draw_numbers, prize, created_at, updated_at, uniq_identifier
FROM lottery_logs
WHERE uniq_identifier = $1
`

type GetLotteryLogsByUniqIdentifierRow struct {
	ID              uuid.UUID
	LotteryID       uuid.UUID
	LotteryRewardID uuid.UUID
	DrawNumbers     [][]int32
	Prize           decimal.Decimal
	CreatedAt       time.Time
	UpdatedAt       time.Time
	UniqIdentifier  uuid.UUID
}

func (q *Queries) GetLotteryLogsByUniqIdentifier(ctx context.Context, uniqIdentifier uuid.UUID) ([]GetLotteryLogsByUniqIdentifierRow, error) {
	rows, err := q.db.Query(ctx, getLotteryLogsByUniqIdentifier, uniqIdentifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLotteryLogsByUniqIdentifierRow
	for rows.Next() {
		var i GetLotteryLogsByUniqIdentifierRow
		if err := rows.Scan(
			&i.ID,
			&i.LotteryID,
			&i.LotteryRewardID,
			&i.DrawNumbers,
			&i.Prize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UniqIdentifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
