// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: manual_funds.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const saveManualFund = `-- name: SaveManualFund :one
INSERT INTO manual_funds (user_id,admin_id,transaction_id,type,amount,reason,currency,note,created_at) VALUES(
  $1,$2,$3,$4,$5,$6,$7,$8,$9
) RETURNING id, user_id, admin_id, transaction_id, type, amount, currency, note, created_at, reason
`

type SaveManualFundParams struct {
	UserID        uuid.UUID
	AdminID       uuid.UUID
	TransactionID string
	Type          string
	Amount        decimal.Decimal
	Reason        string
	Currency      string
	Note          string
	CreatedAt     time.Time
}

func (q *Queries) SaveManualFund(ctx context.Context, arg SaveManualFundParams) (ManualFund, error) {
	row := q.db.QueryRow(ctx, saveManualFund,
		arg.UserID,
		arg.AdminID,
		arg.TransactionID,
		arg.Type,
		arg.Amount,
		arg.Reason,
		arg.Currency,
		arg.Note,
		arg.CreatedAt,
	)
	var i ManualFund
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdminID,
		&i.TransactionID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CreatedAt,
		&i.Reason,
	)
	return i, err
}
