// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

type BetStatus string

const (
	BetStatusOpen       BetStatus = "open"
	BetStatusInProgress BetStatus = "in_progress"
	BetStatusClosed     BetStatus = "closed"
	BetStatusFailed     BetStatus = "failed"
)

func (e *BetStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BetStatus(s)
	case string:
		*e = BetStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BetStatus: %T", src)
	}
	return nil
}

type NullBetStatus struct {
	BetStatus BetStatus
	Valid     bool // Valid is true if BetStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBetStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BetStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BetStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBetStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BetStatus), nil
}

type Components string

const (
	ComponentsRealMoney  Components = "real_money"
	ComponentsBonusMoney Components = "bonus_money"
	ComponentsPoints     Components = "points"
)

func (e *Components) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Components(s)
	case string:
		*e = Components(s)
	default:
		return fmt.Errorf("unsupported scan type for Components: %T", src)
	}
	return nil
}

type NullComponents struct {
	Components Components
	Valid      bool // Valid is true if Components is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComponents) Scan(value interface{}) error {
	if value == nil {
		ns.Components, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Components.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComponents) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Components), nil
}

type Spinningwheelmysterytypes string

const (
	SpinningwheelmysterytypesPoint               Spinningwheelmysterytypes = "point"
	SpinningwheelmysterytypesInternetPackageInGb Spinningwheelmysterytypes = "internet_package_in_gb"
	SpinningwheelmysterytypesBetter              Spinningwheelmysterytypes = "better"
	SpinningwheelmysterytypesOther               Spinningwheelmysterytypes = "other"
)

func (e *Spinningwheelmysterytypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Spinningwheelmysterytypes(s)
	case string:
		*e = Spinningwheelmysterytypes(s)
	default:
		return fmt.Errorf("unsupported scan type for Spinningwheelmysterytypes: %T", src)
	}
	return nil
}

type NullSpinningwheelmysterytypes struct {
	Spinningwheelmysterytypes Spinningwheelmysterytypes
	Valid                     bool // Valid is true if Spinningwheelmysterytypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpinningwheelmysterytypes) Scan(value interface{}) error {
	if value == nil {
		ns.Spinningwheelmysterytypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Spinningwheelmysterytypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpinningwheelmysterytypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Spinningwheelmysterytypes), nil
}

type Spinningwheeltypes string

const (
	SpinningwheeltypesPoint               Spinningwheeltypes = "point"
	SpinningwheeltypesInternetPackageInGb Spinningwheeltypes = "internet_package_in_gb"
	SpinningwheeltypesBetter              Spinningwheeltypes = "better"
	SpinningwheeltypesMystery             Spinningwheeltypes = "mystery"
	SpinningwheeltypesFreespin            Spinningwheeltypes = "free spin"
)

func (e *Spinningwheeltypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Spinningwheeltypes(s)
	case string:
		*e = Spinningwheeltypes(s)
	default:
		return fmt.Errorf("unsupported scan type for Spinningwheeltypes: %T", src)
	}
	return nil
}

type NullSpinningwheeltypes struct {
	Spinningwheeltypes Spinningwheeltypes
	Valid              bool // Valid is true if Spinningwheeltypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpinningwheeltypes) Scan(value interface{}) error {
	if value == nil {
		ns.Spinningwheeltypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Spinningwheeltypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpinningwheeltypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Spinningwheeltypes), nil
}

type AccountBlock struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	BlockedBy   uuid.UUID
	Duration    string
	Type        string
	BlockedFrom sql.NullTime
	BlockedTo   sql.NullTime
	UnblockedAt sql.NullTime
	Reason      sql.NullString
	Note        sql.NullString
	CreatedAt   sql.NullTime
}

type AddsService struct {
	ID            uuid.UUID
	ServiceUrl    string
	Name          string
	ServiceID     string
	ServiceSecret string
	Description   sql.NullString
	Status        string
	CreatedBy     uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type AgentProvider struct {
	ID           uuid.UUID
	ClientID     string
	ClientSecret string
	Status       string
	Name         string
	Description  sql.NullString
	CallbackUrl  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type AgentReferral struct {
	ID               uuid.UUID
	RequestID        string
	CallbackUrl      string
	UserID           uuid.NullUUID
	ConversionType   sql.NullString
	Amount           decimal.NullDecimal
	Msisdn           sql.NullString
	ConvertedAt      sql.NullTime
	CallbackSent     sql.NullBool
	CallbackAttempts sql.NullInt32
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type AirtimeTransaction struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	TransactionID    string
	Cashout          decimal.Decimal
	Billername       string
	Utilitypackageid int32
	Packagename      string
	Amount           decimal.Decimal
	Status           string
	Timestamp        time.Time
}

type AirtimeUtility struct {
	LocalID       uuid.UUID
	ID            int32
	Productname   string
	Billername    string
	Amount        string
	Isamountfixed bool
	Price         decimal.NullDecimal
	Status        string
	Timestamp     time.Time
}

type Balance struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Currency   string
	RealMoney  decimal.NullDecimal
	BonusMoney decimal.NullDecimal
	Points     sql.NullInt32
	UpdatedAt  sql.NullTime
}

type BalanceLog struct {
	ID                  uuid.UUID
	UserID              uuid.NullUUID
	Component           Components
	Currency            sql.NullString
	ChangeAmount        decimal.NullDecimal
	OperationalGroupID  uuid.NullUUID
	OperationalTypeID   uuid.NullUUID
	OperationalTypeName sql.NullString
	Type                sql.NullString
	Description         sql.NullString
	Timestamp           sql.NullTime
	BalanceAfterUpdate  decimal.Decimal
	TransactionID       string
	Status              sql.NullString
}

type SaveBalanceLogsParams struct {
	UserID             uuid.NullUUID
	Component          Components
	Currency           sql.NullString
	ChangeAmount       decimal.NullDecimal
	OperationalGroupID uuid.NullUUID
	OperationalTypeID  uuid.NullUUID
	Description        sql.NullString
	Timestamp          sql.NullTime
	BalanceAfterUpdate decimal.Decimal
	TransactionID      string
	Status             sql.NullString
}

type Banner struct {
	ID        uuid.UUID
	Page      string
	PageUrl   string
	ImageUrl  string
	Headline  string
	Tagline   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Bet struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	RoundID             uuid.UUID
	Amount              decimal.Decimal
	Currency            string
	ClientTransactionID string
	CashOutMultiplier   decimal.NullDecimal
	Payout              decimal.NullDecimal
	Timestamp           sql.NullTime
	Status              sql.NullString
}

type CasbinRule struct {
	ID    int32
	Ptype sql.NullString
	V0    sql.NullString
	V1    sql.NullString
	V2    sql.NullString
	V3    sql.NullString
	V4    sql.NullString
	V5    sql.NullString
}

type Club struct {
	ID        uuid.UUID
	ClubName  string
	Status    sql.NullString
	Timestamp time.Time
}

type Company struct {
	ID                             uuid.UUID
	SiteName                       string
	SupportEmail                   string
	SupportPhone                   string
	MaintenanceMode                sql.NullBool
	MaximumLoginAttempt            sql.NullInt32
	PasswordExpiry                 sql.NullInt32
	LockoutDuration                sql.NullInt32
	RequireTwoFactorAuthentication sql.NullBool
	IpList                         []pgtype.Inet
	CreatedBy                      uuid.UUID
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
	DeletedAt                      sql.NullTime
}

type Config struct {
	ID        uuid.UUID
	Name      string
	Value     string
	CreatedAt time.Time
}

type CryptoKing struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Status             string
	BetAmount          decimal.Decimal
	WonAmount          decimal.NullDecimal
	StartCryptoValue   decimal.Decimal
	EndCryptoValue     decimal.Decimal
	SelectedEndSecond  sql.NullInt32
	SelectedStartValue decimal.NullDecimal
	SelectedEndValue   decimal.NullDecimal
	WonStatus          string
	Type               string
	Timestamp          time.Time
}

type Currency struct {
	ID        uuid.UUID
	Name      string
	Status    string
	Timestamp time.Time
}

type DepartementsUser struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	DepartmentID uuid.UUID
	CreatedAt    sql.NullTime
}

type Department struct {
	ID            uuid.UUID
	Name          string
	Notifications []string
	CreatedAt     sql.NullTime
}

type ExchangeRate struct {
	ID           uuid.UUID
	CurrencyFrom sql.NullString
	CurrencyTo   sql.NullString
	Rate         decimal.NullDecimal
	UpdatedAt    sql.NullTime
}

type FailedBetLog struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	RoundID       uuid.UUID
	BetID         uuid.UUID
	Manual        bool
	AdminID       uuid.NullUUID
	Status        string
	CreatedAt     time.Time
	TransactionID uuid.UUID
}

type FootballMatch struct {
	ID        uuid.UUID
	RoundID   uuid.UUID
	League    string
	Date      time.Time
	HomeTeam  string
	AwayTeam  sql.NullString
	Status    sql.NullString
	Won       sql.NullString
	Timestamp time.Time
	HomeScore sql.NullInt32
	AwayScore sql.NullInt32
}

type FootballMatchRound struct {
	ID        uuid.UUID
	Status    sql.NullString
	Timestamp time.Time
}

type Game struct {
	ID        uuid.UUID
	Name      string
	Status    string
	Timestamp time.Time
	Photo     sql.NullString
	Price     sql.NullString
	Enabled   sql.NullBool
}

type GameLog struct {
	ID        uuid.UUID
	RoundID   uuid.UUID
	Action    string
	Detail    pgtype.JSON
	Timestamp sql.NullTime
}

type IpFilter struct {
	ID          uuid.UUID
	CreatedBy   uuid.UUID
	StartIp     string
	EndIp       string
	Type        string
	CreatedAt   sql.NullTime
	Description string
	Hits        int32
	LastHit     sql.NullTime
}

type League struct {
	ID         uuid.UUID
	LeagueName string
	Status     sql.NullString
	Timestamp  time.Time
}

type Level struct {
	ID        uuid.UUID
	Level     decimal.Decimal
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	CreatedBy uuid.UUID
	Type      string
}

type LevelRequirement struct {
	ID        uuid.UUID
	LevelID   uuid.UUID
	Type      string
	Value     string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	CreatedBy uuid.UUID
}

type Log struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Module    string
	Detail    pgtype.JSON
	IpAddress sql.NullString
	Timestamp sql.NullTime
}

type LoginAttempt struct {
	ID          uuid.UUID
	UserID      uuid.NullUUID
	IpAddress   string
	Success     bool
	AttemptTime sql.NullTime
	UserAgent   sql.NullString
}

type LootBox struct {
	ID          uuid.UUID
	Type        string
	Prizeamount decimal.Decimal
	Weight      decimal.Decimal
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type LootBoxPlaceBet struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	UserSelection uuid.NullUUID
	LootBox       pgtype.JSONB
	Wonstatus     string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Lottery struct {
	ID            uuid.UUID
	Name          string
	Price         decimal.Decimal
	MinSelectable int32
	MaxSelectable int32
	DrawFrequency string
	NumberOfBalls int32
	Description   string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type LotteryLog struct {
	ID              uuid.UUID
	LotteryID       uuid.UUID
	LotteryRewardID uuid.UUID
	Prize           decimal.Decimal
	CreatedAt       time.Time
	UpdatedAt       time.Time
	UniqIdentifier  uuid.UUID
	DrawNumbers     [][]int32
}

type LotteryService struct {
	ID           uuid.UUID
	ClientID     string
	ClientSecret string
	Status       string
	Name         string
	Description  sql.NullString
	CallbackUrl  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type LotteryWinnersLog struct {
	ID              uuid.UUID
	LotteryID       uuid.UUID
	UserID          uuid.UUID
	RewardID        uuid.UUID
	WonAmount       decimal.Decimal
	Currency        string
	NumberOfTickets int32
	TicketNumber    string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ManualFund struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	AdminID       uuid.UUID
	TransactionID string
	Type          string
	Amount        decimal.Decimal
	Currency      string
	Note          string
	CreatedAt     time.Time
	Reason        string
}

type OperationalGroup struct {
	ID          uuid.UUID
	Name        sql.NullString
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type OperationalType struct {
	ID          uuid.UUID
	GroupID     uuid.UUID
	Name        sql.NullString
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Permission struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Plinko struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	BetAmount     decimal.Decimal
	DropPath      string
	Multiplier    decimal.NullDecimal
	WinAmount     decimal.NullDecimal
	Finalposition decimal.NullDecimal
	Timestamp     time.Time
}

type QuickHustle struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Status      string
	BetAmount   decimal.Decimal
	WonStatus   sql.NullString
	UserGuessed sql.NullString
	FirstCard   string
	SecondCard  sql.NullString
	Timestamp   time.Time
	WonAmount   decimal.NullDecimal
}

type RiskSetting struct {
	ID                                int16
	SystemLimitsEnabled               bool
	SystemMaxDailyAirtimeConversion   int64
	SystemMaxWeeklyAirtimeConversion  int64
	SystemMaxMonthlyAirtimeConversion int64
	PlayerLimitsEnabled               bool
	PlayerMaxDailyAirtimeConversion   int32
	PlayerMaxWeeklyAirtimeConversion  int32
	PlayerMaxMonthlyAirtimeConversion int32
	PlayerMinAirtimeConversionAmount  int32
	PlayerConversionCooldownHours     int32
	KycRequiredAboveAmount            int32
	KycVerificationTimeoutHours       int32
	KycAllowPartial                   bool
	FraudMaxLoginAttempts             int16
	FraudLoginLockoutDurationMinutes  int32
	AlertAdminsOnTrigger              bool
	CreatedAt                         time.Time
	UpdatedAt                         time.Time
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type RolePermission struct {
	ID           uuid.UUID
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type RollDaDice struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	Status                string
	BetAmount             decimal.Decimal
	WonStatus             sql.NullString
	CrashPoint            decimal.Decimal
	Timestamp             time.Time
	WonAmount             decimal.NullDecimal
	UserGuessedStartPoint decimal.NullDecimal
	UserGuessedEndPoint   decimal.NullDecimal
	Multiplier            decimal.NullDecimal
}

type Round struct {
	ID         uuid.UUID
	Status     BetStatus
	CrashPoint decimal.Decimal
	CreatedAt  time.Time
	ClosedAt   sql.NullTime
}

type ScratchCard struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Status    string
	BetAmount decimal.Decimal
	WonStatus sql.NullString
	Timestamp time.Time
	WonAmount decimal.NullDecimal
}

type SpinningWheel struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Status    string
	BetAmount string
	Timestamp time.Time
	WonAmount sql.NullString
	WonStatus sql.NullString
	Type      sql.NullString
}

type SpinningWheelConfig struct {
	ID        uuid.UUID
	Name      string
	Amount    decimal.Decimal
	Type      Spinningwheeltypes
	Status    string
	CreatedAt time.Time
	CreatedBy uuid.UUID
	DeletedAt sql.NullTime
	Frequency int32
	Icon      string
	Color     string
}

type SpinningWheelMystery struct {
	ID        uuid.UUID
	Name      string
	Amount    decimal.Decimal
	Type      Spinningwheelmysterytypes
	Status    string
	Frequency int32
	CreatedAt time.Time
	CreatedBy uuid.UUID
	DeletedAt sql.NullTime
	Icon      string
}

type SpinningWheelReward struct {
	ID            uuid.UUID
	RoundID       uuid.UUID
	Name          string
	Amount        decimal.Decimal
	Type          string
	Status        string
	ClaimStatus   string
	TransactionID sql.NullString
	UserID        uuid.UUID
}

type SportBet struct {
	ID              uuid.UUID
	TransactionID   string
	BetAmount       decimal.Decimal
	BetReferenceNum string
	GameReference   string
	BetMode         string
	Description     sql.NullString
	UserID          uuid.UUID
	FrontendType    sql.NullString
	Status          sql.NullString
	SportIds        sql.NullString
	SiteID          string
	ClientIp        sql.NullString
	AffiliateUserID sql.NullString
	Autorecharge    sql.NullString
	BetDetails      pgtype.JSONB
	Currency        string
	PotentialWin    decimal.NullDecimal
	ActualWin       decimal.NullDecimal
	Odds            decimal.NullDecimal
	PlacedAt        time.Time
	SettledAt       sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Squad struct {
	ID        uuid.UUID
	Handle    string
	Owner     uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Type      string
}

type SquadsEarn struct {
	ID        uuid.UUID
	SquadID   uuid.UUID
	UserID    uuid.UUID
	Currency  string
	Earned    decimal.Decimal
	GameID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type SquadsMemeber struct {
	ID        uuid.UUID
	SquadID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type StreetKing struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Status       string
	Version      string
	BetAmount    decimal.Decimal
	WonAmount    decimal.NullDecimal
	CrashPoint   decimal.Decimal
	CashOutPoint decimal.NullDecimal
	Timestamp    time.Time
}

type Temp struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Data      pgtype.JSONB
}

type Tournament struct {
	ID               uuid.UUID
	Rank             string
	Level            int32
	CumulativePoints int32
	Rewards          pgtype.JSONB
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
}

type TournamentsClaim struct {
	ID           uuid.UUID
	TournamentID uuid.UUID
	SquadID      uuid.UUID
	ClaimedAt    time.Time
}

type User struct {
	ID                       uuid.UUID
	Username                 sql.NullString
	PhoneNumber              sql.NullString
	Password                 string
	CreatedAt                time.Time
	DefaultCurrency          sql.NullString
	Profile                  sql.NullString
	Email                    sql.NullString
	FirstName                sql.NullString
	LastName                 sql.NullString
	DateOfBirth              sql.NullString
	Source                   sql.NullString
	IsEmailVerified          sql.NullBool
	ReferalCode              sql.NullString
	StreetAddress            sql.NullString
	Country                  sql.NullString
	State                    sql.NullString
	City                     sql.NullString
	PostalCode               sql.NullString
	KycStatus                sql.NullString
	CreatedBy                uuid.NullUUID
	IsAdmin                  sql.NullBool
	Status                   sql.NullString
	ReferalType              sql.NullString
	ReferedByCode            sql.NullString
	UserType                 sql.NullString
	PrimaryWalletAddress     sql.NullString
	WalletVerificationStatus sql.NullString
}

type UserNotification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Content   string
	Type      string
	Metadata  pgtype.JSONB
	Read      bool
	Delivered bool
	CreatedAt time.Time
	ReadAt    sql.NullTime
	CreatedBy uuid.NullUUID
}

type UserRole struct {
	ID     uuid.UUID
	UserID uuid.UUID
	RoleID uuid.UUID
}

type UserSession struct {
	ID                    uuid.UUID
	UserID                uuid.NullUUID
	Token                 string
	ExpiresAt             time.Time
	IpAddress             sql.NullString
	UserAgent             sql.NullString
	CreatedAt             sql.NullTime
	RefreshToken          sql.NullString
	RefreshTokenExpiresAt sql.NullTime
}

type UsersFootballMatch struct {
	ID                         uuid.UUID
	Status                     string
	MatchID                    uuid.UUID
	Selection                  string
	UsersFootballMatcheRoundID uuid.NullUUID
}

type UsersFootballMatcheRound struct {
	ID              uuid.UUID
	Status          string
	WonStatus       sql.NullString
	UserID          uuid.UUID
	FootballRoundID uuid.NullUUID
	BetAmount       decimal.NullDecimal
	WonAmount       decimal.Decimal
	Timestamp       sql.NullTime
	Currency        string
}

type UsersOtp struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Otp       string
	CreatedAt time.Time
}

type WaitingSquadMember struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	SquadID   uuid.UUID
	CreatedAt time.Time
}
