// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rakeback_override.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

const getActiveGlobalRakebackOverride = `-- name: GetActiveGlobalRakebackOverride :one
SELECT id, is_active, rakeback_percentage, start_time, end_time, created_by, created_at, updated_by, updated_at
FROM global_rakeback_override
WHERE is_active = true
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveGlobalRakebackOverrideRow struct {
	ID                uuid.UUID
	IsActive          bool
	RakebackPercentage decimal.Decimal
	StartTime         sql.NullTime
	EndTime           sql.NullTime
	CreatedBy         pgtype.UUID
	CreatedAt         time.Time
	UpdatedBy         pgtype.UUID
	UpdatedAt         time.Time
}

func (q *Queries) GetActiveGlobalRakebackOverride(ctx context.Context) (GetActiveGlobalRakebackOverrideRow, error) {
	row := q.db.QueryRow(ctx, getActiveGlobalRakebackOverride)
	var i GetActiveGlobalRakebackOverrideRow
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.RakebackPercentage,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalRakebackOverride = `-- name: GetGlobalRakebackOverride :one
SELECT id, is_active, rakeback_percentage, start_time, end_time, created_by, created_at, updated_by, updated_at
FROM global_rakeback_override
ORDER BY created_at DESC
LIMIT 1
`

type GetGlobalRakebackOverrideRow struct {
	ID                uuid.UUID
	IsActive          bool
	RakebackPercentage decimal.Decimal
	StartTime         sql.NullTime
	EndTime           sql.NullTime
	CreatedBy         pgtype.UUID
	CreatedAt         time.Time
	UpdatedBy         pgtype.UUID
	UpdatedAt         time.Time
}

func (q *Queries) GetGlobalRakebackOverride(ctx context.Context) (GetGlobalRakebackOverrideRow, error) {
	row := q.db.QueryRow(ctx, getGlobalRakebackOverride)
	var i GetGlobalRakebackOverrideRow
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.RakebackPercentage,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createGlobalRakebackOverride = `-- name: CreateGlobalRakebackOverride :one
INSERT INTO global_rakeback_override (is_active, rakeback_percentage, start_time, end_time, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, is_active, rakeback_percentage, start_time, end_time, created_by, created_at, updated_by, updated_at
`

type CreateGlobalRakebackOverrideParams struct {
	IsActive          bool
	RakebackPercentage decimal.Decimal
	StartTime         interface{}
	EndTime           interface{}
	CreatedBy         *uuid.UUID
	UpdatedBy         *uuid.UUID
}

type CreateGlobalRakebackOverrideRow struct {
	ID                uuid.UUID
	IsActive          bool
	RakebackPercentage decimal.Decimal
	StartTime         sql.NullTime
	EndTime           sql.NullTime
	CreatedBy         pgtype.UUID
	CreatedAt         time.Time
	UpdatedBy         pgtype.UUID
	UpdatedAt         time.Time
}

func (q *Queries) CreateGlobalRakebackOverride(ctx context.Context, arg CreateGlobalRakebackOverrideParams) (CreateGlobalRakebackOverrideRow, error) {
	row := q.db.QueryRow(ctx, createGlobalRakebackOverride,
		arg.IsActive,
		arg.RakebackPercentage,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i CreateGlobalRakebackOverrideRow
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.RakebackPercentage,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGlobalRakebackOverride = `-- name: UpdateGlobalRakebackOverride :one
UPDATE global_rakeback_override
SET 
    is_active = $2,
    rakeback_percentage = $3,
    start_time = $4,
    end_time = $5,
    updated_by = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, is_active, rakeback_percentage, start_time, end_time, created_by, created_at, updated_by, updated_at
`

type UpdateGlobalRakebackOverrideParams struct {
	ID                uuid.UUID
	IsActive          bool
	RakebackPercentage decimal.Decimal
	StartTime         interface{}
	EndTime           interface{}
	UpdatedBy         *uuid.UUID
}

type UpdateGlobalRakebackOverrideRow struct {
	ID                uuid.UUID
	IsActive          bool
	RakebackPercentage decimal.Decimal
	StartTime         sql.NullTime
	EndTime           sql.NullTime
	CreatedBy         pgtype.UUID
	CreatedAt         time.Time
	UpdatedBy         pgtype.UUID
	UpdatedAt         time.Time
}

func (q *Queries) UpdateGlobalRakebackOverride(ctx context.Context, arg UpdateGlobalRakebackOverrideParams) (UpdateGlobalRakebackOverrideRow, error) {
	row := q.db.QueryRow(ctx, updateGlobalRakebackOverride,
		arg.ID,
		arg.IsActive,
		arg.RakebackPercentage,
		arg.StartTime,
		arg.EndTime,
		arg.UpdatedBy,
	)
	var i UpdateGlobalRakebackOverrideRow
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.RakebackPercentage,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const disableGlobalRakebackOverride = `-- name: DisableGlobalRakebackOverride :exec
UPDATE global_rakeback_override
SET 
    is_active = false,
    updated_by = $2,
    updated_at = NOW()
WHERE id = $1
`

type DisableGlobalRakebackOverrideParams struct {
	ID        uuid.UUID
	UpdatedBy uuid.UUID
}

func (q *Queries) DisableGlobalRakebackOverride(ctx context.Context, arg DisableGlobalRakebackOverrideParams) error {
	_, err := q.db.Exec(ctx, disableGlobalRakebackOverride, arg.ID, arg.UpdatedBy)
	return err
}

