// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: report.sql

package db

import (
	"context"
	"time"
)

const getBucksSpent = `-- name: GetBucksSpent :one
SELECT
    COALESCE(SUM(amount), 0)::int8 AS bucks_spent
FROM airtime_transactions
WHERE DATE(timestamp) = $1
`

func (q *Queries) GetBucksSpent(ctx context.Context, timestamp time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, getBucksSpent, timestamp)
	var bucks_spent int64
	err := row.Scan(&bucks_spent)
	return bucks_spent, err
}

const getPlayerCounts = `-- name: GetPlayerCounts :one
SELECT
    COUNT(*) FILTER (WHERE default_currency IS NOT NULL) AS total_players,
    COUNT(*) FILTER (
        WHERE default_currency IS NOT NULL
          AND DATE(created_at) = $1
    ) AS new_players
FROM users
`

type GetPlayerCountsRow struct {
	TotalPlayers int64
	NewPlayers   int64
}

func (q *Queries) GetPlayerCounts(ctx context.Context, createdAt time.Time) (GetPlayerCountsRow, error) {
	row := q.db.QueryRow(ctx, getPlayerCounts, createdAt)
	var i GetPlayerCountsRow
	err := row.Scan(&i.TotalPlayers, &i.NewPlayers)
	return i, err
}
