// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: risk_settings.sql

package db

import (
	"context"
)

const createOrUpdateRiskSettings = `-- name: CreateOrUpdateRiskSettings :one
INSERT INTO risk_settings (
    id,
    system_limits_enabled,
    system_max_daily_airtime_conversion,
    system_max_weekly_airtime_conversion,
    system_max_monthly_airtime_conversion,
    player_limits_enabled,
    player_max_daily_airtime_conversion,
    player_max_weekly_airtime_conversion,
    player_max_monthly_airtime_conversion,
    player_min_airtime_conversion_amount,
    player_conversion_cooldown_hours,
    kyc_required_above_amount,
    kyc_verification_timeout_hours,
    kyc_allow_partial,
    fraud_max_login_attempts,
    fraud_login_lockout_duration_minutes,
    alert_admins_on_trigger
) VALUES (
    1, -- The required ID for the singleton row
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (id) DO UPDATE SET
    system_limits_enabled = EXCLUDED.system_limits_enabled,
    system_max_daily_airtime_conversion = EXCLUDED.system_max_daily_airtime_conversion,
    system_max_weekly_airtime_conversion = EXCLUDED.system_max_weekly_airtime_conversion,
    system_max_monthly_airtime_conversion = EXCLUDED.system_max_monthly_airtime_conversion,
    player_limits_enabled = EXCLUDED.player_limits_enabled,
    player_max_daily_airtime_conversion = EXCLUDED.player_max_daily_airtime_conversion,
    player_max_weekly_airtime_conversion = EXCLUDED.player_max_weekly_airtime_conversion,
    player_max_monthly_airtime_conversion = EXCLUDED.player_max_monthly_airtime_conversion,
    player_min_airtime_conversion_amount = EXCLUDED.player_min_airtime_conversion_amount,
    player_conversion_cooldown_hours = EXCLUDED.player_conversion_cooldown_hours,
    kyc_required_above_amount = EXCLUDED.kyc_required_above_amount,
    kyc_verification_timeout_hours = EXCLUDED.kyc_verification_timeout_hours,
    kyc_allow_partial = EXCLUDED.kyc_allow_partial,
    fraud_max_login_attempts = EXCLUDED.fraud_max_login_attempts,
    fraud_login_lockout_duration_minutes = EXCLUDED.fraud_login_lockout_duration_minutes,
    alert_admins_on_trigger = EXCLUDED.alert_admins_on_trigger,
    updated_at = NOW()
RETURNING id, system_limits_enabled, system_max_daily_airtime_conversion, system_max_weekly_airtime_conversion, system_max_monthly_airtime_conversion, player_limits_enabled, player_max_daily_airtime_conversion, player_max_weekly_airtime_conversion, player_max_monthly_airtime_conversion, player_min_airtime_conversion_amount, player_conversion_cooldown_hours, kyc_required_above_amount, kyc_verification_timeout_hours, kyc_allow_partial, fraud_max_login_attempts, fraud_login_lockout_duration_minutes, alert_admins_on_trigger, created_at, updated_at
`

type CreateOrUpdateRiskSettingsParams struct {
	SystemLimitsEnabled               bool
	SystemMaxDailyAirtimeConversion   int64
	SystemMaxWeeklyAirtimeConversion  int64
	SystemMaxMonthlyAirtimeConversion int64
	PlayerLimitsEnabled               bool
	PlayerMaxDailyAirtimeConversion   int32
	PlayerMaxWeeklyAirtimeConversion  int32
	PlayerMaxMonthlyAirtimeConversion int32
	PlayerMinAirtimeConversionAmount  int32
	PlayerConversionCooldownHours     int32
	KycRequiredAboveAmount            int32
	KycVerificationTimeoutHours       int32
	KycAllowPartial                   bool
	FraudMaxLoginAttempts             int16
	FraudLoginLockoutDurationMinutes  int32
	AlertAdminsOnTrigger              bool
}

func (q *Queries) CreateOrUpdateRiskSettings(ctx context.Context, arg CreateOrUpdateRiskSettingsParams) (RiskSetting, error) {
	row := q.db.QueryRow(ctx, createOrUpdateRiskSettings,
		arg.SystemLimitsEnabled,
		arg.SystemMaxDailyAirtimeConversion,
		arg.SystemMaxWeeklyAirtimeConversion,
		arg.SystemMaxMonthlyAirtimeConversion,
		arg.PlayerLimitsEnabled,
		arg.PlayerMaxDailyAirtimeConversion,
		arg.PlayerMaxWeeklyAirtimeConversion,
		arg.PlayerMaxMonthlyAirtimeConversion,
		arg.PlayerMinAirtimeConversionAmount,
		arg.PlayerConversionCooldownHours,
		arg.KycRequiredAboveAmount,
		arg.KycVerificationTimeoutHours,
		arg.KycAllowPartial,
		arg.FraudMaxLoginAttempts,
		arg.FraudLoginLockoutDurationMinutes,
		arg.AlertAdminsOnTrigger,
	)
	var i RiskSetting
	err := row.Scan(
		&i.ID,
		&i.SystemLimitsEnabled,
		&i.SystemMaxDailyAirtimeConversion,
		&i.SystemMaxWeeklyAirtimeConversion,
		&i.SystemMaxMonthlyAirtimeConversion,
		&i.PlayerLimitsEnabled,
		&i.PlayerMaxDailyAirtimeConversion,
		&i.PlayerMaxWeeklyAirtimeConversion,
		&i.PlayerMaxMonthlyAirtimeConversion,
		&i.PlayerMinAirtimeConversionAmount,
		&i.PlayerConversionCooldownHours,
		&i.KycRequiredAboveAmount,
		&i.KycVerificationTimeoutHours,
		&i.KycAllowPartial,
		&i.FraudMaxLoginAttempts,
		&i.FraudLoginLockoutDurationMinutes,
		&i.AlertAdminsOnTrigger,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRiskSettings = `-- name: GetRiskSettings :one

SELECT id, system_limits_enabled, system_max_daily_airtime_conversion, system_max_weekly_airtime_conversion, system_max_monthly_airtime_conversion, player_limits_enabled, player_max_daily_airtime_conversion, player_max_weekly_airtime_conversion, player_max_monthly_airtime_conversion, player_min_airtime_conversion_amount, player_conversion_cooldown_hours, kyc_required_above_amount, kyc_verification_timeout_hours, kyc_allow_partial, fraud_max_login_attempts, fraud_login_lockout_duration_minutes, alert_admins_on_trigger, created_at, updated_at FROM risk_settings
WHERE id = 1
`

// risk_settings.sql - Queries for the singleton risk settings table
func (q *Queries) GetRiskSettings(ctx context.Context) (RiskSetting, error) {
	row := q.db.QueryRow(ctx, getRiskSettings)
	var i RiskSetting
	err := row.Scan(
		&i.ID,
		&i.SystemLimitsEnabled,
		&i.SystemMaxDailyAirtimeConversion,
		&i.SystemMaxWeeklyAirtimeConversion,
		&i.SystemMaxMonthlyAirtimeConversion,
		&i.PlayerLimitsEnabled,
		&i.PlayerMaxDailyAirtimeConversion,
		&i.PlayerMaxWeeklyAirtimeConversion,
		&i.PlayerMaxMonthlyAirtimeConversion,
		&i.PlayerMinAirtimeConversionAmount,
		&i.PlayerConversionCooldownHours,
		&i.KycRequiredAboveAmount,
		&i.KycVerificationTimeoutHours,
		&i.KycAllowPartial,
		&i.FraudMaxLoginAttempts,
		&i.FraudLoginLockoutDurationMinutes,
		&i.AlertAdminsOnTrigger,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
