// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: spinning_wheels.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createSpinningWheel = `-- name: CreateSpinningWheel :one
INSERT INTO spinning_wheels (user_id,status,bet_amount,timestamp,won_amount,won_status,type)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, user_id, status, bet_amount, timestamp, won_amount, won_status, type
`

type CreateSpinningWheelParams struct {
	UserID    uuid.UUID
	Status    string
	BetAmount string
	Timestamp time.Time
	WonAmount sql.NullString
	WonStatus sql.NullString
	Type      sql.NullString
}

func (q *Queries) CreateSpinningWheel(ctx context.Context, arg CreateSpinningWheelParams) (SpinningWheel, error) {
	row := q.db.QueryRow(ctx, createSpinningWheel,
		arg.UserID,
		arg.Status,
		arg.BetAmount,
		arg.Timestamp,
		arg.WonAmount,
		arg.WonStatus,
		arg.Type,
	)
	var i SpinningWheel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.BetAmount,
		&i.Timestamp,
		&i.WonAmount,
		&i.WonStatus,
		&i.Type,
	)
	return i, err
}

const createSpinningWheelConfig = `-- name: CreateSpinningWheelConfig :one
INSERT INTO spinning_wheel_configs (name,amount,type,frequency,created_by,created_at,icon, color) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, name, amount, type, status, created_at, created_by, deleted_at, frequency, icon, color
`

type CreateSpinningWheelConfigParams struct {
	Name      string
	Amount    decimal.Decimal
	Type      Spinningwheeltypes
	Frequency int32
	CreatedBy uuid.UUID
	CreatedAt time.Time
	Icon      string
	Color     string
}

func (q *Queries) CreateSpinningWheelConfig(ctx context.Context, arg CreateSpinningWheelConfigParams) (SpinningWheelConfig, error) {
	row := q.db.QueryRow(ctx, createSpinningWheelConfig,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.Frequency,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.Icon,
		arg.Color,
	)
	var i SpinningWheelConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.Frequency,
		&i.Icon,
		&i.Color,
	)
	return i, err
}

const createSpinningWheelMysteries = `-- name: CreateSpinningWheelMysteries :one
INSERT INTO spinning_wheel_mysteries (name,amount,type,status,frequency,created_by,created_at,icon) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, name, amount, type, status, frequency, created_at, created_by, deleted_at, icon
`

type CreateSpinningWheelMysteriesParams struct {
	Name      string
	Amount    decimal.Decimal
	Type      Spinningwheelmysterytypes
	Status    string
	Frequency int32
	CreatedBy uuid.UUID
	CreatedAt time.Time
	Icon      string
}

func (q *Queries) CreateSpinningWheelMysteries(ctx context.Context, arg CreateSpinningWheelMysteriesParams) (SpinningWheelMystery, error) {
	row := q.db.QueryRow(ctx, createSpinningWheelMysteries,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.Status,
		arg.Frequency,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.Icon,
	)
	var i SpinningWheelMystery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Frequency,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.Icon,
	)
	return i, err
}

const deleteSpinningWheelConfig = `-- name: DeleteSpinningWheelConfig :exec
Update spinning_wheel_configs set deleted_at = now() where id = $1
`

func (q *Queries) DeleteSpinningWheelConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpinningWheelConfig, id)
	return err
}

const deleteSpinningWheelMystery = `-- name: DeleteSpinningWheelMystery :exec
Update spinning_wheel_mysteries set deleted_at = now() where id = $1
`

func (q *Queries) DeleteSpinningWheelMystery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpinningWheelMystery, id)
	return err
}

const getAllSpinningWheelConfigs = `-- name: GetAllSpinningWheelConfigs :many
SELECT id,name,amount,type,frequency,status,icon FROM spinning_wheel_configs where deleted_at is null
`

type GetAllSpinningWheelConfigsRow struct {
	ID        uuid.UUID
	Name      string
	Amount    decimal.Decimal
	Type      Spinningwheeltypes
	Frequency int32
	Status    string
	Icon      string
}

func (q *Queries) GetAllSpinningWheelConfigs(ctx context.Context) ([]GetAllSpinningWheelConfigsRow, error) {
	rows, err := q.db.Query(ctx, getAllSpinningWheelConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSpinningWheelConfigsRow
	for rows.Next() {
		var i GetAllSpinningWheelConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.Frequency,
			&i.Status,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSpinningWheelMysteries = `-- name: GetAllSpinningWheelMysteries :many
SELECT id,name,amount,type,frequency,status,icon FROM spinning_wheel_mysteries where deleted_at is null
`

type GetAllSpinningWheelMysteriesRow struct {
	ID        uuid.UUID
	Name      string
	Amount    decimal.Decimal
	Type      Spinningwheelmysterytypes
	Frequency int32
	Status    string
	Icon      string
}

func (q *Queries) GetAllSpinningWheelMysteries(ctx context.Context) ([]GetAllSpinningWheelMysteriesRow, error) {
	rows, err := q.db.Query(ctx, getAllSpinningWheelMysteries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSpinningWheelMysteriesRow
	for rows.Next() {
		var i GetAllSpinningWheelMysteriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.Frequency,
			&i.Status,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpinningWheelConfig = `-- name: GetSpinningWheelConfig :many
WITH spinning_wheel_configs_data AS (
    SELECT id, name, amount, type, status, created_at, created_by, deleted_at, frequency, icon, color
    FROM spinning_wheel_configs where deleted_at is null
),
row_count AS (
    SELECT COUNT(*) AS total_rows
    FROM spinning_wheel_configs_data where deleted_at is null
)
SELECT s.name, s.amount, s.type, s.frequency, r.total_rows
FROM spinning_wheel_configs_data s
CROSS JOIN row_count r
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type GetSpinningWheelConfigParams struct {
	Limit  int32
	Offset int32
}

type GetSpinningWheelConfigRow struct {
	Name      string
	Amount    decimal.Decimal
	Type      Spinningwheeltypes
	Frequency int32
	TotalRows int64
}

func (q *Queries) GetSpinningWheelConfig(ctx context.Context, arg GetSpinningWheelConfigParams) ([]GetSpinningWheelConfigRow, error) {
	rows, err := q.db.Query(ctx, getSpinningWheelConfig, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpinningWheelConfigRow
	for rows.Next() {
		var i GetSpinningWheelConfigRow
		if err := rows.Scan(
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.Frequency,
			&i.TotalRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpinningWheelConfigs = `-- name: GetSpinningWheelConfigs :many
WITH spinning_wheel_configs_data AS (
    SELECT id, name, amount, type, status, created_at, created_by, deleted_at, frequency, icon, color
    FROM spinning_wheel_configs where deleted_at is null
),
row_count AS (
    SELECT COUNT(*) AS total_rows
    FROM spinning_wheel_configs_data  where deleted_at is null
)
SELECT s.id, s.name, s.amount, s.type, s.frequency, r.total_rows,s.icon, s.color
FROM spinning_wheel_configs_data s
CROSS JOIN row_count r
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type GetSpinningWheelConfigsParams struct {
	Limit  int32
	Offset int32
}

type GetSpinningWheelConfigsRow struct {
	ID        uuid.UUID
	Name      string
	Amount    decimal.Decimal
	Type      Spinningwheeltypes
	Frequency int32
	TotalRows int64
	Icon      string
	Color     string
}

func (q *Queries) GetSpinningWheelConfigs(ctx context.Context, arg GetSpinningWheelConfigsParams) ([]GetSpinningWheelConfigsRow, error) {
	rows, err := q.db.Query(ctx, getSpinningWheelConfigs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpinningWheelConfigsRow
	for rows.Next() {
		var i GetSpinningWheelConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.Frequency,
			&i.TotalRows,
			&i.Icon,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpinningWheelMysteries = `-- name: GetSpinningWheelMysteries :many
WITH spinning_wheel_mysteries_data AS (
    SELECT id, name, amount, type, status, frequency, created_at, created_by, deleted_at, icon
    FROM spinning_wheel_mysteries
    WHERE deleted_at is null
),
row_count AS (
    SELECT COUNT(*) AS total_rows
    FROM spinning_wheel_mysteries_data
)
SELECT s.id, s.name, s.amount, s.type, s.frequency,s.status, r.total_rows,s.icon
FROM spinning_wheel_mysteries_data s
CROSS JOIN row_count r
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type GetSpinningWheelMysteriesParams struct {
	Limit  int32
	Offset int32
}

type GetSpinningWheelMysteriesRow struct {
	ID        uuid.UUID
	Name      string
	Amount    decimal.Decimal
	Type      Spinningwheelmysterytypes
	Frequency int32
	Status    string
	TotalRows int64
	Icon      string
}

func (q *Queries) GetSpinningWheelMysteries(ctx context.Context, arg GetSpinningWheelMysteriesParams) ([]GetSpinningWheelMysteriesRow, error) {
	rows, err := q.db.Query(ctx, getSpinningWheelMysteries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpinningWheelMysteriesRow
	for rows.Next() {
		var i GetSpinningWheelMysteriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.Frequency,
			&i.Status,
			&i.TotalRows,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpinningWheelUserHistory = `-- name: GetSpinningWheelUserHistory :many
WITH spinning_wheels_data AS (
    SELECT id, user_id, status, bet_amount, timestamp, won_amount, won_status, type
    FROM spinning_wheels
    WHERE user_id = $1 and status = 'CLOSED' 
),
row_count AS (
    SELECT COUNT(*) AS total_rows
    FROM spinning_wheels_data
     WHERE user_id = $1 AND status = 'CLOSED'
)
SELECT c.id, c.user_id, c.status, c.bet_amount, c.timestamp, c.won_amount, c.won_status, c.type, r.total_rows
FROM spinning_wheels_data c
CROSS JOIN row_count r
ORDER BY c.timestamp DESC
LIMIT $2 OFFSET $3
`

type GetSpinningWheelUserHistoryParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type GetSpinningWheelUserHistoryRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Status    string
	BetAmount string
	Timestamp time.Time
	WonAmount sql.NullString
	WonStatus sql.NullString
	Type      sql.NullString
	TotalRows int64
}

func (q *Queries) GetSpinningWheelUserHistory(ctx context.Context, arg GetSpinningWheelUserHistoryParams) ([]GetSpinningWheelUserHistoryRow, error) {
	rows, err := q.db.Query(ctx, getSpinningWheelUserHistory, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpinningWheelUserHistoryRow
	for rows.Next() {
		var i GetSpinningWheelUserHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.BetAmount,
			&i.Timestamp,
			&i.WonAmount,
			&i.WonStatus,
			&i.Type,
			&i.TotalRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpinningWheelConfig = `-- name: UpdateSpinningWheelConfig :one
UPDATE spinning_wheel_configs set status = $1,updated_at = now(),frequency = $3, amount = $4,name = $5,type = $6 where id = $2 RETURNING id, name, amount, type, status, created_at, created_by, deleted_at, frequency, icon, color
`

type UpdateSpinningWheelConfigParams struct {
	Status    string
	ID        uuid.UUID
	Frequency int32
	Amount    decimal.Decimal
	Name      string
	Type      Spinningwheeltypes
}

func (q *Queries) UpdateSpinningWheelConfig(ctx context.Context, arg UpdateSpinningWheelConfigParams) (SpinningWheelConfig, error) {
	row := q.db.QueryRow(ctx, updateSpinningWheelConfig,
		arg.Status,
		arg.ID,
		arg.Frequency,
		arg.Amount,
		arg.Name,
		arg.Type,
	)
	var i SpinningWheelConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.Frequency,
		&i.Icon,
		&i.Color,
	)
	return i, err
}

const updateSpinningWheelMystery = `-- name: UpdateSpinningWheelMystery :one
UPDATE spinning_wheel_mysteries set status = $1,updated_at = now(),frequency = $3, amount = $4,name = $5,type = $6 where id = $2 RETURNING id, name, amount, type, status, frequency, created_at, created_by, deleted_at, icon
`

type UpdateSpinningWheelMysteryParams struct {
	Status    string
	ID        uuid.UUID
	Frequency int32
	Amount    decimal.Decimal
	Name      string
	Type      Spinningwheelmysterytypes
}

func (q *Queries) UpdateSpinningWheelMystery(ctx context.Context, arg UpdateSpinningWheelMysteryParams) (SpinningWheelMystery, error) {
	row := q.db.QueryRow(ctx, updateSpinningWheelMystery,
		arg.Status,
		arg.ID,
		arg.Frequency,
		arg.Amount,
		arg.Name,
		arg.Type,
	)
	var i SpinningWheelMystery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Frequency,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.Icon,
	)
	return i, err
}
