// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_notifications.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM user_notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) FROM user_notifications
WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT
    id,
    user_id,
    title,
    content,
    type,
    metadata,
    read,
    delivered,
    created_by,
    read_at,
    created_at,
    COUNT(*) OVER() AS total
FROM
    user_notifications
WHERE
    user_id = $1
ORDER BY
    created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserNotificationsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type GetUserNotificationsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Content   string
	Type      string
	Metadata  pgtype.JSONB
	Read      bool
	Delivered bool
	CreatedBy uuid.NullUUID
	ReadAt    sql.NullTime
	CreatedAt time.Time
	Total     int64
}

func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]GetUserNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getUserNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNotificationsRow
	for rows.Next() {
		var i GetUserNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Type,
			&i.Metadata,
			&i.Read,
			&i.Delivered,
			&i.CreatedBy,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserNotification = `-- name: InsertUserNotification :one
INSERT INTO user_notifications (
    user_id, title, content, type, metadata, read, delivered, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING
    id,
    user_id,
    title,
    content,
    type,
    metadata,
    read,
    delivered,
    created_by,
    read_at,
    created_at
`

type InsertUserNotificationParams struct {
	UserID    uuid.UUID
	Title     string
	Content   string
	Type      string
	Metadata  pgtype.JSONB
	Read      bool
	Delivered bool
	CreatedBy uuid.NullUUID
}

type InsertUserNotificationRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Content   string
	Type      string
	Metadata  pgtype.JSONB
	Read      bool
	Delivered bool
	CreatedBy uuid.NullUUID
	ReadAt    sql.NullTime
	CreatedAt time.Time
}

func (q *Queries) InsertUserNotification(ctx context.Context, arg InsertUserNotificationParams) (InsertUserNotificationRow, error) {
	row := q.db.QueryRow(ctx, insertUserNotification,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.Type,
		arg.Metadata,
		arg.Read,
		arg.Delivered,
		arg.CreatedBy,
	)
	var i InsertUserNotificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Type,
		&i.Metadata,
		&i.Read,
		&i.Delivered,
		&i.CreatedBy,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE user_notifications
SET read = TRUE, read_at = NOW()
WHERE user_id = $1 AND (read = FALSE OR read IS NULL)
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE user_notifications
SET read = TRUE, read_at = NOW()
WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
