ALTER TABLE users
ADD COLUMN street_address VARCHAR NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN country VARCHAR NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN state VARCHAR NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN city VARCHAR NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN postal_code VARCHAR NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN kyc_status VARCHAR NOT NULL DEFAULT 'PENDING';

