ALTER TABLE game_providers
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS api_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS webhook_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS integration_type VARCHAR(50) DEFAULT 'API' CHECK (integration_type IN ('API', 'WEBHOOK', 'BOTH')),
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;